#logging:
 # level:
  #  root: DEBUG
server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PolarBookshop/config-repo.git
          #uri: file://${HOME}/music-app/config-repo
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          skip-ssl-validation: true

